[package]
name = "rust_rdbms_practice"
version = "0.1.0"
authors = ["ryosukeeeee <ryou.fm.bros@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
